spring.application.name=taskboard
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskboard}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:taskboard}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:taskboard}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:asdfiejwinmvkdsnajfeidknkcmxzdfewasdfhgjhhtjkbvcqpoiuwercvjkcjbnmv}
app.jwt.expiration-minutes=60